version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  openvas:
      image: "mikesplain/openvas:9"
      restart: unless-stopped
      env_file:
        - .env
      logging: *default-logging
      volumes:
       - "${BASE_PATH:-/data}/openvas:/var/lib/openvas/mgr"
      networks:
        - default
        - web
      labels:
        - "deck-chores.dump.command=sh -c \"greenbone-nvt-sync; openvasmd --rebuild --progress\""
        - "deck-chores.dump.interval=daily"
        - "traefik.backend=naturalis-openvas"
        - "traefik.enable=true"
        - "traefik.port=443"
        - "${SITE_URL-traefik.frontend.rule=Host:openvas.site.nl}"
 # Daily updates to openvas
  cron:
      restart: unless-stopped
      image: funkyfuture/deck-chores
      logging: *default-logging
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
      image: traefik:1.7.10
      container_name: traefik
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
        - 8081:8080
      networks:
        - default
        - web
      logging: *default-logging
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${BASE_PATH:-/data}/traefiklogs/traefik.log:/var/log/traefik.log
        - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
        - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt


# run docker network create web before
networks:
  web:
    external: true

