version: '3'
services:
  openvas:
    image: "mikesplain/openvas"
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - "8443:443"
    volumes:
     - "/data:/var/lib/openvas/mgr"
    networks:
      - default
      - web
    labels:
      - "deck-chores.dump.command=sh -c \"greenbone-nvt-sync; openvasmd --rebuild --progress\""
      - "deck-chores.dump.interval=daily"
      - "traefik.backend=naturalis.nl"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=8443"
      - ${OPENVAS_URL_CONFIG:-traefik.frontend.rule=Host:openvas.naturalis.nl}
  traefik:
    image: traefik:1.6.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
 # Daily updates to openvas
  cron:
    restart: always
    image: funkyfuture/deck-chores
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

# run docker network create web before
networks:
  web:
    external: true

