version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  openvas:
      image: "naturalis/openvas:7.0.3"
      restart: unless-stopped
      env_file:
        - .env
      logging: *default-logging
      volumes:
       - "${BASE_PATH:-/data}/openvas:/var/lib/openvas/mgr"
      networks:
        - default
      labels:
        - "deck-chores.dump.command=sh -c \"greenbone-nvt-sync; openvasmd --rebuild --progress\""
        - "deck-chores.dump.interval=daily"
        - traefik.enable=${TRAEFIK_ENABLE:-true}
        - traefik.http.routers.openvas.entrypoints=https
        - traefik.http.routers.openvas.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-route53}
        - traefik.http.routers.openvas.tls=true
        - traefik.http.routers.openvas.rule=${SITE_URL:-Host(`openvas.naturalis.nl`)}


  traefik:
    image: traefik:2.1
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    logging: *default-logging



# Daily updates to openvas
  cron:
      restart: unless-stopped
      image: funkyfuture/deck-chores
      logging: *default-logging
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

# run docker network create web before
networks:
  web:
    external: true

