version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  openvas:
      image: "mikesplain/openvas:9"
      restart: unless-stopped
      env_file:
        - .env
      logging: *default-logging
      ports:
        - "8443:443"
      volumes:
       - "${BASE_PATH:-/data}/openvas:/var/lib/openvas/mgr"
      networks:
        - default
        - web
      labels:
        - "deck-chores.dump.command=sh -c \"greenbone-nvt-sync; openvasmd --rebuild --progress\""
        - "deck-chores.dump.interval=daily"

services:
  nginx:
      image: nginx:alpine
      restart: unless-stopped
      hostname: nginx
      ports:
        - "80:80"
      links:
        - openvas
      logging: *default-logging
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt

# This Nginx requires the certificates to exist, otherwise will fail
  nginx_ssl:
      image: nginx:alpine
      restart: unless-stopped
      hostname: nginx_ssl
      ports:
        - "443:443"
      links:
        - openvas
      logging: *default-logging
      volumes:
        - ./nginx_ssl.conf:/etc/nginx/nginx.conf:ro
        - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt
        
# Daily updates to openvas
  cron:
      restart: unless-stopped
      image: funkyfuture/deck-chores
      logging: *default-logging
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

# run docker network create web before
networks:
  web:
    external: true

